### ISSUE TITLE
Issue with custom price string

### ISSUE THREAD

**Issue by trixovino3** [Prospress/woocommerce-subscriptions-custom-price-string#3]
Hello, 
your team very helpfully recommended a custom price string to me the other day, as I didn't like the usual subscription pricing format when a synchronized renewal subscription is priced up. 

I've installed the plug in but the problem is that it has removed the price from the product when it is shown on the home page, and indeed on the product pages. it only shows on the product details page, which is a problem. Do you know what I have done wrong?

Also, to truly customize this I'd love to change the colour of the price and add the pound sign. do you know how I can do that? thank you!

Victoria

**Comment by bernattorras** [comment]
Hi Victoria,

Thanks for reporting this issue! 

I suspect that the problem that you're experiencing could be related to your theme (maybe it is using different filters/functionality to display the products on the home page or their details on the product page). 

In any case, I'd like to take a deeper look at this issue on your site to confirm it and see if we need to fix anything from our side. 

As we're already handling this issue on your support ticket, I'll close the issue here. In case it is indeed an issue from our side, I'll create a new issue in our repository with the required details and we'll work on it from there to get it fixed as soon as possible. 

Again, thanks for your collaboration! :)
Bernat
